---
title: "Vehicle Crash Severity Correlating Factors"
author:
- name: Samuel Runyan
  email: samyan@byu.edu
  affiliation: Brigham Young University
  footnote: 1
date: "`r Sys.Date()`"
address:
- code: Brigham Young University
  address: Civil and Environmental Engineering Department, 430 Engineering Building,
    Provo, Utah 84602
site: bookdown::bookdown_site
documentclass: article
journal: Findings
bibliography: book.bib
biblio-style: apalike
link-citations: yes
abstract: |
  Crash data from the state of Utah was analyzed to answer the question, "what variables correlate to crash severity?". Variables related to manner of collision, presence of schools near crashes, and presence of transit stops near crashes were considered in this analysis. It was determined that angle crashes at intersections and same-direction sideswipe crashes at roadway segments were more strongly correlated to crash severity, but the presence of schools and transit stops did not have a strong correlation to crash severity. There is a considerable correlation between pedestrian involvement and crash severity, so different variables related to pedestrian presence could be used to build a crash severity model.
description: The purpose of this article is to identify the most significant correlating factors to crash severity when performing highway safety analysis.
layout: 3p, authoryear
keywords:
- Highway Safety Analysis
- Crash Severity
- Statistical Correlation
---

# QUESTIONS {#intro}


<!-- maybe talk about how this relates to above. Give context on who they are and what they did. -->
@ghadi2020 attempted to determine the impact of environmental variables on crash severity, but few others have added to this research. The purpose of this article is to identify any additional factors that may correlate to crash severity such as the manner of collision, and variables related to the presence of pedestrians. The results of this article will help determine which of these variables are significant enough to include in severity-weighted network screening. In the past, many network screening models have been limited by precedent, but this research aims to expound on and improve tried and tested methods. With better understanding of how crash variables relate to crash severity, it may be possible to more proactively prevent severe crashes rather than waiting for them to happen before they can be modeled.

A major difficulty with most current network screening methodologies is that they do not account for the influence of crash severity towards the overall potential for safety improvement (PSI) of roadways. Therefore, it is valuable to use a crash severity-weighted approach when performing network screening. @yasmin2018 and @afghari2020 assert that a joint crash count with crash severity model is best suited to identify sites with the most PSI because of the correlation between crash counts and crash severity. As part of this joint model, it may be helpful to consider other factors which may contribute to the crash severity distribution at a given site. 